apiVersion: v1
kind: Secret
metadata:
  name: {{ include "backend.fullname" . }}-secrets
type: Opaque
data:
  {{- if .Values.secrets.openaiApiKey }}
  openai-api-key: {{ .Values.secrets.openaiApiKey | b64enc | quote }}
  {{- end }}
  {{- if .Values.secrets.authSecret }}
  auth-secret: {{ .Values.secrets.authSecret | b64enc | quote }}
  {{- end }}
  {{- if .Values.secrets.databaseUrl }}
  database-url: {{ .Values.secrets.databaseUrl | b64enc | quote }}
  {{- end }}
  {{- if .Values.secrets.dbPassword }}
  pgpassword: {{ .Values.secrets.dbPassword | b64enc | quote }}
  {{- end }}